@TOKEN = 

POST http://localhost:3000/user
Content-Type: application/json

{
    "name": "John Doe",
    "email": "john.doe@example.com",
    "password": "default"
}

###
POST http://localhost:3000/user/login
Content-Type: application/json

{
    "email": "john.doe@example.com",
    "password": "default"
}

###
GET http://localhost:3000/user/protected
Authorization: Bearer {{TOKEN}}
Content-Type: application/json
